s = set()
n = int(input("Enter a number: "))
s.add(n)
n = int(input("Enter a number: "))
s.add(n)
n = int(input("Enter a number: "))
s.add(n)
n = int(input("Enter a number: "))
s.add(n)
n = int(input("Enter a number: "))
s.add(n)
n = int(input("Enter a number: "))
s.add(n)
n = int(input("Enter a number: "))
s.add(n)
n = int(input("Enter a number: "))
s.add(n)

print(s)